Print error if NDDSHOME points to wrong thing

diff --git a/connext_cmake_module/env_hook/connext.sh.in b/connext_cmake_module/env_hook/connext.sh.in
--- a/connext_cmake_module/env_hook/connext.sh.in
+++ b/connext_cmake_module/env_hook/connext.sh.in
@@ -16,6 +16,12 @@ if [ -z "$NDDSHOME" ]; then
   export NDDSHOME=$_DEFAULT_NDDSHOME
 fi
 
+if [ ! -d "$NDDSHOME" ]; then
+  echo "[connext_cmake_module] Error: NDDSHOME environment variable does not point to a valid directory: \"$NDDSHOME\"" 1>&2
+  unset _DEFAULT_NDDSHOME
+  return
+fi
+
 # detect if running on Darwin platform
 _UNAME=`uname -s`
 _IS_DARWIN=0
